export const attachment = [  
    {  
       "AttachmentId":1,
       "FileName":"Requirement.doc",
       "FilePath":"It785 (wireless keyboard)",
       "ParentId":1,
       "GrandParentId":2,
       "Size":"143KB"
    }
 ,  
    {  
        "AttachmentId":2,
        "FileName":"OptiPortal.doc",
        "FilePath":"c/doc/attachement/",
        "ParentId":2,
        "GrandParentId":1,
        "Size":"143KB"
    }
  ,
    {  
        "AttachmentId":3,
        "FileName":"Requirement.doc",
        "FilePath":"It785 (wireless keyboard)",
        "ParentId":5,
        "GrandParentId":2,
        "Size":"143KB"
     }
  ,  
     {  
         "AttachmentId":4,
         "FileName":"report.pdf",
         "FilePath":"c/doc/attachement/",
         "ParentId":1,
         "GrandParentId":1,
        "Size":"143KB"
     }
     ,
     {  
        "AttachmentId":5,
        "FileName":"Requirement.doc",
        "FilePath":"It785 (wireless keyboard)",
        "ParentId":5,
        "GrandParentId":2,
        "Size":"143KB"
     }
  ,  
     {  
         "AttachmentId":6,
         "FileName":"report.PPTX",
         "FilePath":"c/doc/attachement/",
         "ParentId":1,
         "GrandParentId":1,
         "Size":"729KB"
     }
     ,
     {  
        "AttachmentId":7,
        "FileName":"meeting.PPT",
        "FilePath":"It785 (wireless keyboard)",
        "ParentId":5,
        "GrandParentId":2,
        "Size":"512KB"
     }
  ,  
     {  
         "AttachmentId":8,
         "FileName":"sample.txt",
         "FilePath":"c/doc/attachement/",
         "ParentId":1,
         "GrandParentId":1,
         "Size":"974KB"
     }
     ,  
     {  
         "AttachmentId":9,
         "FileName":"estimates.xls",
         "FilePath":"c/doc/attachement/",
         "ParentId":1,
         "GrandParentId":1,
         "Size":"246KB"
     }
]